# 🧠 DOCKER COMPOSE - SYSTÈME TRADING AUTONOME
version: '3.8'

services:
  # 🧠 SYSTÈME AUTONOME PRINCIPAL
  autonomous_trading:
    build:
      context: .
      dockerfile: Dockerfile.autonomous
    container_name: trading_ai_autonomous
    environment:
      # Configuration Système
      - DEMO_MODE=true  # Mode simulation sans APIs payantes
      - INITIAL_CAPITAL=200
      - PORT=8000
      - LOG_LEVEL=INFO
      
      # Base de données (optionnel pour simulation)
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB:-trading_ai}
      - POSTGRES_USER=${POSTGRES_USER:-trader}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-TradingDB2025!}
      
      # APIs Gratuites (optionnel)
      - DEMO_API_MODE=true
      
      # Configuration Docker
      - PYTHONUNBUFFERED=1
      
    volumes:
      - ./logs/autonomous:/app/logs
      - ./data/autonomous:/app/data
      - ./backup/autonomous:/app/backup
    ports:
      - "${AUTONOMOUS_PORT:-8000}:8000"
    networks:
      - trading_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Limites mémoire simples (compatibles)
    mem_limit: 512m
    memswap_limit: 512m

  # 🗃️ POSTGRESQL - BASE DE DONNÉES (optionnel pour stats)
  postgres:
    image: postgres:15-alpine
    container_name: trading_ai_postgres_autonomous
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-trading_ai}
      - POSTGRES_USER=${POSTGRES_USER:-trader}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-TradingDB2025!}
    volumes:
      - postgres_autonomous_data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    networks:
      - trading_network
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER:-trader} -d ${POSTGRES_DB:-trading_ai}']
      interval: 5s
      timeout: 5s
      retries: 10

  # 📊 GRAFANA - DASHBOARDS PROFESSIONNELS (optionnel)
  grafana:
    image: grafana/grafana:latest
    container_name: trading_ai_grafana_autonomous
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-TradingAI2025!}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/trading-dashboard.json
    volumes:
      - grafana_autonomous_data:/var/lib/grafana
      - ./logs/grafana:/var/log/grafana
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./configs/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    networks:
      - trading_network
    restart: unless-stopped
    depends_on:
      - postgres
      - prometheus
    # Limite mémoire simple
    mem_limit: 256m
    profiles:
      - professional  # Démarrer seulement en mode pro

  # 📈 PROMETHEUS - MÉTRIQUES SYSTÈME (optionnel)
  prometheus:
    image: prom/prometheus:latest
    container_name: trading_ai_prometheus_autonomous
    volumes:
      - prometheus_autonomous_data:/prometheus
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    networks:
      - trading_network
    restart: unless-stopped
    # Limite mémoire simple
    mem_limit: 256m
    profiles:
      - professional  # Démarrer seulement en mode pro

  # 🌐 NGINX - REVERSE PROXY SIMPLE
  nginx:
    image: nginx:alpine
    container_name: trading_ai_nginx_autonomous
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./configs/nginx/autonomous.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - autonomous_trading
      - grafana
    networks:
      - trading_network
    restart: unless-stopped

# 🔗 RÉSEAUX
networks:
  trading_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 💾 VOLUMES
volumes:
  postgres_autonomous_data:
    driver: local
  grafana_autonomous_data:
    driver: local
  prometheus_autonomous_data:
    driver: local

# 🔧 CONFIGURATION VARIABLES D'ENVIRONNEMENT
# Créer un fichier .env avec :
# POSTGRES_PASSWORD=TradingDB2025!
# GF_ADMIN_PASSWORD=TradingAI2025!
# AUTONOMOUS_PORT=8000
# GRAFANA_PORT=3000
# HTTP_PORT=80 