server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: trading-ai-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: grafana
          __path__: /var/log/grafana/*.log

      - targets:
          - localhost
        labels:
          job: postgresql
          __path__: /var/log/postgresql/*.log

      - targets:
          - localhost
        labels:
          job: n8n
          __path__: /var/log/n8n/*.log

      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log