# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "trading_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'trading-ai'
    static_configs:
      - targets: ['host.docker.internal:8080'] # N8N metrics endpoint

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093